---
- name: Install Apache and configure web servers
  hosts: apache_servers
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present
        update_cache: true

    - name: Start and enable Apache
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copy index.html to Apache document root
      copy:
        src: index.html
        dest: /var/www/html/index.html
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted


